### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by Gazler** [scrogson/guardian#1]
Hi,

I created a Phoenix project that I am using to test Guardian in its current state. It is available at https://github.com/Gazler/guardian_test, the specific commit for the Guardian features is https://github.com/Gazler/guardian_test/commit/07e5d11b3e61cf600f709dda0252f83593baebe0

I have also added a couple of things to Guardian, I would just like to confirm that this is the way it is intended to be used, if not then if you can advise and I will pull-request open a pull request with that. https://github.com/Gazler/guardian/commit/2ceb4b8f7ed1164563698847faaf6498caa08361

Thanks.

**Comment by scrogson** [comment]
This is not ready for the World yet. Hopefully later on I'll have more time to pour into it.
